### ISSUE TITLE
[bug] Rune Saved Sets DB error

### ISSUE THREAD

**Issue by illutian** [Road-block/RuneSets#1]
I get this.. I assume it's because I have no saved Rune presets and there's no 'catch' for that.

42x RuneSets/SetsUI.lua:1141: attempt to index field 'db' (a nil value)
[string "@RuneSets/SetsUI.lua"]:1141: in function `UpdateSetList'
[string "@RuneSets/SetsUI.lua"]:1279: in function <RuneSets/SetsUI.lua:1277>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2168: in function `SetUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2013: in function `ShowUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1881: in function <Interface_Vanilla/FrameXML/UIParent.lua:1877>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2660: in function `ShowUIPanel'
[string "@StatWeightsClassic/shared/core.lua"]:153: in function `?'
[string "@StatWeightsClassic/shared/ui.lua"]:2535: in function <StatWeightsClassic/shared/ui.lua:2534>

Locals:
self = RuneSetsFrame {
 contentFrame = RuneSetsFrameContentFrame {
 }
 toggleButton = RuneSetsFrameToggleButton {
 }
 collapsed = true
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"
addon = <table> {
 utils = <table> {
 }
 ADDON_LOADED = <function> defined @RuneSets/SetsUI.lua:697
 PLAYER_ENTERING_WORLD = <function> defined @RuneSets/SetsUI.lua:716
 Minimap = <table> {
 }
 PLAYER_EQUIPMENT_CHANGED = <function> defined @RuneSets/SetsUI.lua:761
 NEW_RECIPE_LEARNED = <function> defined @RuneSets/SetsUI.lua:768
 L = <table> {
 }
 _label = "|cff008080RuneSets|r"
 SetButton = <table> {
 }
 UNIT_INVENTORY_CHANGED = <function> defined @RuneSets/SetsUI.lua:745
 RUNE_UPDATED = <function> defined @RuneSets/SetsUI.lua:751
 GROUP_FORMED = <function> defined @RuneSets/SetsUI.lua:734
 RunSet = <function> defined @RuneSets/SetsUI.lua:784
 ZONE_CHANGED_NEW_AREA = <function> defined @RuneSets/SetsUI.lua:734
 _event = Frame {
 }
 Frame = <table> {
 }
 runeCache = <table> {
 }
 GROUP_LEFT = <function> defined @RuneSets/SetsUI.lua:734
}
MAX_RUNESETS = 10
slotid_to_icon = <table> {
 7 = "iconLegs"
 1 = "iconHead"
 15 = "iconBack"
 8 = "iconFeet"
 9 = "iconWrists"
 5 = "iconChest"
 10 = "iconHands"
 3 = "iconShoulders"
 6 = "iconWaist"
}
icon_to_tex = <table> {
 iconShoulders = 136526
 iconHead = 136516
 iconBack = 136512
 iconChest = 136512
 iconFeet = 136513
 iconWrists = 136530
 iconLegs = 136517
 iconHands = 136515
 iconWaist = 136529
}
L = <table> {
 World-Party = "World-Party"
 Apply RuneSet 2 = "Apply RuneSet 2"
 Dungeon = "Dungeon"
 <empty RuneSet> = "<empty RuneSet>"
 Apply RuneSet 7 = "Apply RuneSet 7"
 Include in Menus = "Include in Menus"
 Edit Sets = "Edit Sets"
 Apply RuneSet 3 = "Apply RuneSet 3"
 World-Solo = "World-Solo"
 World-Raid = "World-Raid"
 Minimap = "Minimap"
 Apply RuneSet 1 = "Apply RuneSet 1"
 Raid = "Raid"
 Link Set to Status = "Link Set to Status"
 PvP = "PvP"
 Apply RuneSet 6 = "Apply RuneSet 6"
 Toggle Engraving Frame = "Toggle Engraving Frame"
 Apply RuneSet 8 = "Apply RuneSet 8"
 Apply RuneSet 5 = "Apply RuneSet 5"
 Auto Show = "Auto Show"
 RuneSet Binds = "RuneSet Binds"
 Apply RuneSet 4 = "Apply RuneSet 4"
}
RUNESET_BUTTON_HEIGHT = 32

**Comment by Road-block** [comment]
No that can't be it. You must have a previous error that causes this one.

I'll hop on SoD to check, maybe they changed something in a recent patch as I haven't logged in last couple weeks.

**Comment by Road-block** [comment]
The addon Stat Weights Classic causes this error.

I will try to find out why but unload it even if temporarily and test to verify.

**Comment by Road-block** [comment]
Alright it is forcing the CharacterFrame to show on PLAYER_LOGIN before the UI has fully loaded.
There is no reason to do that to cache rune information.

They could simply call `C_Engraving.RefreshRunesList()` (and ideally do it after PLAYER_ENTERING_WORLD when most of the UI has loaded)

[@jezzi23](https://github.com/jezzi23)

**Comment by illutian** [comment]
> The addon Stat Weights Classic causes this error.
> 
> I will try to find out why but unload it even if temporarily and test to verify.

Disabled SWC and it appears the "db error" has stopped.

((Not sure if I should close this or leave it open. At your discretion.))
