### ISSUE TITLE
Cloak and ring runes issue on v.1.2.8

### ISSUE THREAD

**Issue by Wilford1990** [Road-block/RuneSets#7]
Good day to you, dear MrFIXIT!

There is still few issues on SOD: 

1. Still can't apply a cloak rune (it's visible in the addon after an update but it's unable to apply in your rune set);

2. Can't apply both ring runes (it's visible in the addon after an update but you can apply only one ring rune, 2nd rune still unable to attach in your rune set).

Please fix it when u will be able. 

Best Regards,

Wilford from Living Flame (EU)

**Comment by Road-block** [comment]
1.3.0 might have fixed this.
I'll wait for some community feedback before I close the issue.

**Comment by mkavalecz** [comment]
Applying the back rune works now, but adding it to a set doesn't. Ring runes work correctly.

**Comment by Road-block** [comment]
> Applying the back rune works now, but adding it to a set doesn't. Ring runes work correctly.

Can you test 1.3.1 at your convenience 🙏🏻
